name: cow-edge
title: Cow Edge Network
base: core22
version: '0.0.1'
summary: Edge component of the Cow network.
description: Edge component of the Cow network.
license: Apache-2.0
source-code: https://github.com/dot-5g/cow-edge
issues: https://github.com/dot-5g/cow-edge/issues
architectures:
  - amd64

grade: devel
confinement: strict

apps:
  cow-edge:
    command: bin/cow-edge --config $SNAP/config/config.yaml
    plugs: 
      - network-bind
      - network-control


parts:
  cow-edge:
    build-snaps:
      - go/1.21/stable
    build-packages:
      - libpcap-dev
    stage-packages:
      - libpcap0.8
    plugin: go
    source: .

  config:
    plugin: dump
    source: config.yaml
    source-type: file
    organize:
      config.yaml: config/config.yaml
