name: cow-edge
base: core22
version: '0.0.1'
summary: Cow Edge Network
description: Cow Edge Network

grade: devel
confinement: strict

apps:
  cow-edge:
    command: bin/cow-edge --config $SNAP/config/config.yaml
    plugs: 
      - network-bind

parts:
  cow-edge:
    build-snaps:
      - go/1.21/stable
    plugin: go
    source: .

  config:
    plugin: dump
    source: config.yaml
    source-type: file
    organize:
      config.yaml: config/config.yaml
